### ISSUE TITLE
Apparent conflict with Geocoder when installing official Google API wrapper

### ISSUE THREAD

**Issue by mattlangan** [alexreisner/geocoder#1602]
### Expected behavior

Running `Geocoder.search('Texas State Capitol')` returns the expected result

### Actual behavior

Running `Geocoder.search('Texas State Capitol')` returns `NoMethodError (undefined method 'new' for Google:Module)`

### Steps to reproduce

Run `gem install google-apis-youtube_v3`

### Environment info

* Geocoder version: 1.8.0
* Rails version: 6.0.2
* Database (if applicable): 
* Lookup (if applicable): Google

**Comment by alexreisner** [comment]
Thanks for reporting this! This issue may have been fixed in version 1.8.1 (specifically by #1588). Can you try upgrading and see if that fixes it?

**Comment by b-nik** [comment]
Still an issue on 1.8.1. What's strange is running it a second time right after will work.
