### ISSUE TITLE
SSL with Smarty Streets

### ISSUE THREAD

**Issue by GolfyMcG** [alexreisner/geocoder#825]
I received the following email from Smarty Streets:

> We have identified your account as one that is currently connecting to our system over an insecure, plaintext connection. Running over plaintext exposes your security credentials to theft and makes your customer data available to anyone listening on the wire.
To prevent these and other similar kinds of problems, we will start requiring secure (TLS/SSL) connections to our backend APIs on Thursday, March 26, 2015. After this time, plaintext connections to port 80 on our system will no longer function.
Typically, the only change you'll need to make in your code is change your connection to our system from http to https (simply add the letter 's').

I'm using geocoder to connect to SmartyStreets though, so I wanted to check two things:

1. Since SmartyStreets will no longer be accepting requests over http (as of this Thursday), will the most recent version of this gem automatically enforce that? Or at the very least should the docs be updated?
2. In the meantime (or going forward), how would I go about enforcing this? Is this no different than the google API where I should just include `Geocoder.configure(:use_https => true)`?

**Comment by alexreisner** [comment]
Thanks for the heads-up on this. Yes, `Geocoder.configure(:use_https => true)` is all you need to do, but it does seem like the code should be updated to force SSL with SmartyStreets.

**Comment by alexreisner** [comment]
Fixed: 7342234fe

**Comment by GolfyMcG** [comment]
@alexreisner - thanks for the quick reply!

**Comment by GolfyMcG** [comment]
I'm still experiencing some issues with this but was hoping to be able to examine the HTTP logs associated with Geocoder. Do you have a way of doing that?

**Comment by dleve123** [comment]
@alexreisner colleague of @GolfyMcG here. Just wanted to follow up about the ability to view Geocoder and/or the lower-level generated HTTP requests logs?

Thanks a ton for your help!

**Comment by alexreisner** [comment]
You can set a logger using `Geocoder.configure(logger: ...)` but logging was added recently and there's not yet much in the way of output from Geocoder itself. (HTTP request-level output is not yet included.) I think what you probably want to do is configure Net::HTTP to log debug-level messages.

**Comment by dleve123** [comment]
@alexreisner Yeah looks like nothing is logged? I set configured Geocoder to use the `Rails.logger` and have set `config.log_level = :debug` in `config/environments/development.rb`...

Any suggestions as to how I could controller the `Net::HTTP` logging level? Seems like there's a development-only instance [method](http://ruby-doc.org/stdlib-2.2.1/libdoc/net/http/rdoc/Net/HTTP.html#method-i-set_debug_output) exposed, but that would require latching onto the instance of `Net::HTTP` that Geocoder uses. Is there a simple / suggested way to do that?

Thanks again!

**Comment by alexreisner** [comment]
Since it needs to be done anyway, I just added HTTP request logging to Geocoder. Try installing from master/HEAD, setting your log level to :debug and let me know if that works for you?

**Comment by dleve123** [comment]
@alexreisner Will do. It looks like we figured what was going on by checking out the Geocoder cache keys (which seem to match geocoding API endpoints), but looking forward to testing out the logging functionality.
